[book]
authors = ["francis-du"]
language = "en"
multilingual = false
src = "src"
title = "Wiki Graph Docs"

[output.html]
cname = "wiki-graph.francis.run"
git-repository-url = "https://github.com/francis-du/mdbook-grogu-theme"