name: mdbook-deploy

on:
  push:
    branches: [ main ]

jobs:
  mdbook-deploy:
    name: Mdbook Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: mdbook build docs
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.DEPLOY_KEY}}
          publish_dir: ./docs/book